language: ruby

sudo: false

rvm:
  - 3.0
  - 2.7
  - 2.6
  - 2.5

gemfile:
  - gemfiles/activemodel5.gemfile
  - gemfiles/activemodel6.gemfile

jobs:
  exclude:
    - rvm: 3.0
      gemfile: gemfiles/activemodel5.gemfile

before_install:
  - gem install bundler
